- name: install packages
  apt:
    name: tcpdump

- name: make config directory
  file:
    path: /etc/tcpdumpd/
    state: directory

- name: place files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - {"src": tcpdumpd.service, "dest":/usr/lib/systemd/system/, "mode":"0644"}
    - {"src": tcpdumpd-watcher.service, "dest":/usr/lib/systemd/system/, "mode":"0644"}
    - {"src": tcpdumpd-watcher.path, "dest":/usr/lib/systemd/system/, "mode":"0644"}
    - {"src": tcpdumpd.sh, "dest":/usr/local/sbin/, "mode":"0755"}
    - {"src": tcpdumpd.conf, "dest":/etc/tcpdumpd/, "mode":"0644"}

- name: enable services
  systemd:
    name: "{{ item }}"
    daemon-reload: yes
    state: started
    enabled: yes
  with_items:
    - tcpdumpd
    - tcpdumpd-watcher.path

- name: add samba share for data
  import_role:
    name: add_samba_share
  vars:
    share_name: tcpdump
    share_path: /var/log/tcpdump

- name: add samba share for config
  import_role:
    name: add_samba_share
  vars:
    share_name: etc_tcpdumpd
    share_path: /etc/tcpdumpd/
  